openapi: 3.0.0
info:
  title: Glasswall Transaction Event Store API
  description: These are HTTP endpoints that query the transaction store
  version: 0.1.9
servers:
  - url: http://localhost:32769
    description: Local Dev HTTP
  - url: http://localhost:32768
    description: Local Dev HTTPS
paths:
  /api/v1/transactions:
    post:
      summary: Gets a set of transactions matching the criteria set in the request body
      description: This endpoint accepts an input JSON body containing criteria to search for transactions.
      requestBody:
        content:
          "application/json":
            schema:
              type: object
              required:
                - Filter
              properties:
                Filter:
                  type: object
                  description: An object containing the filtering parameters
                  properties:
                    TimestampRangeStart: 
                      type: string
                      example: "0001-01-01T00:00:00.0000000+00:00"
                    TimestampRangeEnd:
                      type: string
                      example: "9999-12-31T23:59:59.9999999+00:00"
                    Risk:
                      type: array
                      example:
                        - 0
                        - 1
                        - 2
                      items:
                        type: number
                        description: >
                          Each value indicates the risk of a file to filter upon:
                          <br/><br/>* `16` - Safe,
                          <br/><br/>* `17` - Blocked,
                          <br/><br/>* `18` - Allowed
                    DetectionFileType:
                      type: array
                      example:
                        - 16
                        - 19
                        - 33
                      items:
                        type: number
                        description: >
                          Each value indicates a file type in the list of Glasswall supported file types to filter upon:
                          <br/><br/>* `16` - Pdf,
                          <br/><br/>* `17` - Doc,
                          <br/><br/>* `18` - Docx,
                          <br/><br/>* `19` - Ppt,
                          <br/><br/>* `20` - Pptx,
                          <br/><br/>* `21` - Xls,
                          <br/><br/>* `22` - Xlsx,
                          <br/><br/>* `23` - Png,
                          <br/><br/>* `24` - Jpeg,
                          <br/><br/>* `25` - Gif,
                          <br/><br/>* `26` - Emf,
                          <br/><br/>* `27` - Wmf,
                          <br/><br/>* `28` - Rtf,
                          <br/><br/>* `29` - Bmp,
                          <br/><br/>* `30` - Tiff,
                          <br/><br/>* `31` - Pe,
                          <br/><br/>* `32` - Macho,
                          <br/><br/>* `33` - Elf,
                          <br/><br/>* `34` - Mp4,
                          <br/><br/>* `35` - Mp3,
                          <br/><br/>* `36` - Mp2,
                          <br/><br/>* `37` - Wav,
                          <br/><br/>* `38` - Mpg,
                          <br/><br/>* `39` - Coff
                    FileId: 
                      type: array
                      example: 
                        - deadbeef-dead-beef-dead-beeffeedbeef
                        - 125ccda2-a6c6-4f48-adb4-fe04cd42676b
                    Policy: 
                      type: array
                      example: 
                        - deadbeef-dead-beef-dead-beeffeedbeef
                        - 125ccda2-a6c6-4f48-adb4-fe04cd42676b
      responses:
        200:    # status code
          description: OK - The transactions were retrieved successfully
          content:          
            "application/json":
              schema:
                type: object
                properties:
                  message:
                    type: string
        400:
          description: Bad Request - This can occur when the JSON input is malformed, missing parameters or contains invalid parameters
        415:
          description: Unsupported Media Type - This happens when the request was not sent in JSON.
